ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1001
ARG PGID=1001
ENV STNODEFAULTFOLDER=1
#
RUN set -xe \
    && addgroup -g ${PGID} -S syncthing \
    && adduser -u ${PUID} -G syncthing -h /home/syncthing -s /bin/nologin -D syncthing \
    && apk add --no-cache --purge -uU curl ca-certificates \
    && VERSION=$(curl -SL https://api.github.com/repos/syncthing/syncthing/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_v__') \
    && echo "Using version: $VERSION" \
    && curl -o /tmp/syncthing-linux-arm-v${VERSION}.tar.gz -SL https://github.com/syncthing/syncthing/releases/download/v${VERSION}/syncthing-linux-arm-v${VERSION}.tar.gz \
    && tar zxf /tmp/syncthing-linux-arm-v${VERSION}.tar.gz -C /usr/local \
    && ln -s /usr/local/syncthing-linux-arm-v${VERSION}/syncthing /usr/local/bin \
    && chown -R syncthing:syncthing /usr/local/syncthing-linux-arm-v${VERSION}/ \
    && chown -R syncthing:syncthing /usr/local/bin \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME /home/syncthing/
#
EXPOSE 8384 22000 21027/udp
#
ENTRYPOINT ["/init"]
