#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

SYNCTHING_HOME="${SYNCTHING_HOME:-/var/syncthing}";
STHOMEDIR="${STHOMEDIR:-$SYNCTHING_HOME/config}";

# default folder creation is turned off, so for custom data dirs
# ensure top-level directory is owned by syncthing so subfolders
# can be created/synced from gui/application
SYNCTHING_DATA="${SYNCTHING_DATA:-$SYNCTHING_HOME/data}";

vecho "Ensure default configuration directories exist.";
mkdir -p \
    "${SYNCTHING_HOME}" \
    "${STHOMEDIR}" \
    "${SYNCTHING_DATA}" \
    ;

# fix permissions
if [ -z "${SYNCTHING_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown -R \
        ${S6_USER:-alpine}:${PGID:-1000} \
        "${STHOMEDIR}" \
        ;

    # not running chown -R over datadir
    chown \
        ${S6_USER:-alpine}:${PGID:-1000} \
        "${SYNCTHING_HOME}" \
        "${SYNCTHING_DATA}" \
        ;
fi;
